"""Descriptor-driven loading of version-specific database transitions."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from app.db.migrations import DATABASE_NAMES, MigrationError


@dataclass(frozen=True)
class Transition:
    transition_id: str
    directory: Path
    descriptor: Path
    entrypoint: Path
    checksum: str
    order: int
    databases: tuple[str, ...]

    def load(self):
        name = "token_board_transition_" + self.transition_id.replace("-", "_")
        spec = importlib.util.spec_from_file_location(name, self.entrypoint)
        if spec is None or spec.loader is None:
            raise MigrationError(f"cannot load transition module {self.entrypoint}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module


def _digest(directory: Path, paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.relative_to(directory).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def discover(schema_root: str | Path) -> list[Transition]:
    root = Path(schema_root).resolve() / "transitions"
    if not root.is_dir():
        return []
    result: list[Transition] = []
    seen: set[str] = set()
    for directory in sorted(path for path in root.iterdir() if path.is_dir()):
        descriptor = directory / "transition.json"
        if not descriptor.is_file():
            continue
        try:
            data = json.loads(descriptor.read_text(encoding="utf-8"))
            transition_id = str(data["id"])
            entrypoint = directory / str(data["entrypoint"])
            order = int(data.get("order", 1000))
            databases = tuple(str(name) for name in data["databases"])
        except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
            raise MigrationError(f"invalid transition descriptor: {descriptor}") from exc
        if not databases or any(name not in DATABASE_NAMES for name in databases):
            raise MigrationError(
                f"transition {transition_id} names an unknown database: {databases}")
        if len(set(databases)) != len(databases):
            raise MigrationError(f"transition {transition_id} repeats a database")
        if transition_id in seen:
            raise MigrationError(f"duplicate transition id: {transition_id}")
        if not entrypoint.is_file():
            raise MigrationError(f"transition entrypoint not found: {entrypoint}")
        seen.add(transition_id)
        # Generated bytecode must not change the transition identity between
        # two runs.  The descriptor and every source/data file are otherwise
        # part of the checksum, so changing a transition after publication is
        # detected rather than silently replayed.
        files = sorted(
            path for path in directory.rglob("*")
            if path.is_file()
            and "__pycache__" not in path.parts
            and path.suffix != ".pyc"
        )
        result.append(Transition(
            transition_id, directory, descriptor, entrypoint,
            _digest(directory, files), order, databases))
    result.sort(key=lambda item: (item.order, item.transition_id))
    return result


def _table_exists(conn, name: str) -> bool:
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone() is not None


def transition_record(path: Path, transition: Transition) -> tuple[str, str] | None:
    import sqlite3
    if not path.exists():
        return None
    conn = sqlite3.connect(path)
    try:
        if not _table_exists(conn, "schema_transitions"):
            return None
        row = conn.execute(
            "SELECT checksum,generation_id FROM schema_transitions "
            "WHERE transition_id=?", (transition.transition_id,)
        ).fetchone()
        if row and row[0] != transition.checksum:
            raise MigrationError(
                f"checksum mismatch for transition {transition.transition_id}")
        return tuple(row) if row else None
    finally:
        conn.close()


def record_transition(path: Path, transition: Transition,
                      generation_id: str) -> None:
    import sqlite3
    conn = sqlite3.connect(path)
    try:
        conn.execute(
            "CREATE TABLE IF NOT EXISTS schema_transitions(" 
            "transition_id TEXT PRIMARY KEY,checksum TEXT NOT NULL," 
            "generation_id TEXT NOT NULL,applied_at TEXT NOT NULL)"
        )
        conn.execute(
            "INSERT INTO schema_transitions(transition_id,checksum,generation_id,applied_at) "
            "VALUES(?,?,?,strftime('%Y-%m-%dT%H:%M:%fZ','now')) "
            "ON CONFLICT(transition_id) DO UPDATE SET checksum=excluded.checksum, "
            "generation_id=excluded.generation_id,applied_at=excluded.applied_at",
            (transition.transition_id, transition.checksum, generation_id),
        )
        conn.commit()
    finally:
        conn.close()
